home_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'home_app'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='home_app:login'), name='logout'),
    path('register/', views.RegisterPage.as_view(), name='register'),

    path('', views.Tasklist.as_view(), name='tasks'),
    path('detail/<int:pk>/', views.DetailTask.as_view(), name='detail'),
    path('task-create/', views.TaskCreate.as_view(), name='create'),
    path('task-update/<int:pk>/', views.TaskUpdate.as_view(), name='update'),
    path('task-delete/<int:pk>/', views.DeleteTask.as_view(), name='delete'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
]

home_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title) + ' | '+ str(self.user)

    class Meta:
        ordering = ['complete']

home_app/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


class RegisterPage(FormView):
    template_name = 'home_app/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True      # didin't work
    success_url = reverse_lazy('home_app:tasks')
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
    
    def get(self, *args, **kwargs):     # an already logged in user will be redirected
        if self.request.user.is_authenticated:
            return redirect('home_app:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)

class CustomLoginView(LoginView):
    template_name = 'home_app/login.html'
    fields = '__all__'
    redirect_authenticated_user = True   # an already logged in user will be redirected

    def get_success_url(self):
        return reverse_lazy('home_app:tasks')

# Create your views here.
class Tasklist(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks' # custom name
    # task_list.html is the template
    def get_context_data(self, **kwargs):               # for showing only logged in users list
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user) # context_object_name
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains=search_input)

        context['search_input'] = search_input
        return context
    

class DetailTask(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'home_app/task.html' # custom name and path

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ('title', 'description', 'complete')
    success_url = reverse_lazy('home_app:tasks') # only works when you submit the form
    # task_form.html is the template

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ('title', 'description', 'complete')
    success_url = reverse_lazy('home_app:tasks')
    def get(self, *args, **kwargs):
        print(self.request.user.id)     # User class
        # print(Task.objects.filter(user=self.request.user.id))
        print('hello')
        return super(TaskUpdate, self).get(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskUpdate, self).form_valid(form)

class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task' # custom name
    success_url = reverse_lazy('home_app:tasks')

home_app/templates/home_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <title>To Do Items</title>
    <style>
        body {
            background-color: rgb(248, 248, 248);
            font-family: 'Nunito', sans-serif;
            padding-top: 50px;
        }
        .container{
            max-width: 550px;
            margin: auto;
            background-color: rgb(255, 255, 255);
            -webkit-box-shadow:2px 2px 13px -4px rgba(0,0,0,0.21);
            box-shadow:2px 2px 13px -4px rgba(0,0,0,0.21);
        }
        a,p{
            color: #4b5156;
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #EEA390 0%, #EB796F 43%, #EB796F 100%);
        }
        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }
        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding:20px;
            background-color: #fff;
            border-top: 1px solid #dfe4ea;
        }
        .task-title{
            display: flex;
        }
        .task-title a{
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }
        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(105, 192, 105);
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius: 50%;
        }
        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
            padding: 20px 0px;
        }
        #add-link {
            color: #EB796F;
            text-decoration: none;
            font-size: 42px;
            /* text-shadow: 1px 1px #81413b; */
        }

        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }
        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #EB796F;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px !important;
            display: block;
        }

        .button {
            margin-left: 2px;
            border: 1px solid #EB796F;
            background-color: #FAFAFA;
            color: #EB796F;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        #form_dj{
            margin-left:20px;
            padding-bottom: 20px;
        }

    </style>
</head>

<body>
    <div class="container">
        {% block body_block %}
        {% endblock body_block %}
    </div>
</body>

</html>

home_app/templates/home_app/login.html
{% extends 'home_app/base.html' %}
{% block body_block %}
<h1 class="header-bar">Login</h1>
<form id=form_dj method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input class="button" type="submit" value="Login">
</form>
<p style="margin-left: 20px;" >Don't have an account? <a href="{% url 'home_app:register' %}">Register</a></p>
{% endblock body_block %}

home_app/templates/home_app/register.html
{% extends 'home_app/base.html' %}
{% block body_block %}
<h1 class="header-bar">Register</h1>
<form id="form_dj" method="POST">
    {% csrf_token %}
    <label>{{ form.username.label }}</label>
    {{form.username}}
    <label>{{ form.password1.label }}</label>
    {{form.password1}}
    <label>{{ form.password2.label }}</label>
    {{form.password2}}
    <input style="margin-top:10px;" class="button" type="submit" value="Register">
</form>
<p style="margin-left: 20px;">Already have an account? <a href="{% url 'home_app:login' %}">Login</a></p>
{% endblock body_block %}

home_app/templates/home_app/task.html
<h1>Task:</h1>
<h3>{{task}}</h3>
<h3>Title: {{task.title}}</h3>
<h3>Description: {{task.description}}</h3>
<h3>Status: {{task.completed}}</h3>
<h3>Dated: {{task.created}}</h3>

home_app/templates/home_app/task_confirm_delete.html
{% extends 'home_app/base.html' %}
{% block body_block %}
<h1 class="header-bar"><a href={% url 'home_app:tasks' %}>&#10096; Back<a></a></h1> 
        <form id="form_dj" method='POST'>
            {% csrf_token %}
            <p>Are you sure you want to delete task "{{task.title}}"</p>
            <input class="button" type="submit" value="Delete">
        </form>
{% endblock body_block %}

home_app/templates/home_app/task_form.html
{% extends 'home_app/base.html' %}
{% block body_block %}
<h1 class="header-bar"><a href="{% url 'home_app:tasks' %}" >&#10096; Back</a></h1>
<a href={% url 'home_app:tasks' %}></a>
<form id=form_dj method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input class=button type="submit" value="Submit">
</form>
{% endblock body_block %}

home_app/templates/home_app/task_list.html
{% extends 'home_app/base.html' %}
{% block body_block %}

<div class="header-bar">
    <div>
        <h1>Hello {{request.user | title }}</h1>
        <h3 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:'s'}}</h3>
    </div>
    {% if request.user.is_authenticated %}
    <a href={% url 'home_app:logout' %}>Logout</a>
    {% else %}
    <a href={% url 'home_app:login' %}>Login</a>
    {% endif %}
</div>


<div id="search-add-wrapper">
    <form method="GET" style="margin-top:20px;display:flex;">
        <input type="text" name="search-area" value="{{search_input}}">
        <input class="button" type="submit" value="search">
    </form>
    <a id="add-link" href={% url 'home_app:create' %}>&#x2b;</a></td>
</div>

<!-- <h1>My to do list</h1>



<form method="GET">
    <input type="text" name="search-area" value="{{search_input}}">
    <input type="submit" value="search">
</form> -->

<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper" data-position="{{task.pk}}">
        <div class="task-title">
            {% if task.complete %}
                <div class="task-complete-icon"></div>
                <i><s><a href="{% url 'home_app:update' task.id %}">{{task.title}}</a></s></i>
                {% else %}
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'home_app:update' task.id %}">{{task.title}}</a> 
            {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'home_app:delete' task.id %}">&#215;</a>
            <!-- <span class="handle">&nbsp;&#10247;</span> -->
        </div>
    </div>

    {% empty %}
    <h3 style="margin-left: 20px;">No items in list</h3>
    {% endfor %}
</div>



{% endblock body_block %}